name: Generate artifacts

on:
  push:
    branches: [ "develop", "master" ]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [MobileAndroid, Dmg, Deb, Msi]
